/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CTA = IDL.Variant({
  'scheduleTestDrive' : IDL.Null,
  'visitDealership' : IDL.Null,
  'getQuote' : IDL.Null,
});
export const Model = IDL.Variant({
  'mustang' : IDL.Null,
  'f150' : IDL.Null,
  'explorer' : IDL.Null,
});
export const Time = IDL.Int;
export const Tone = IDL.Variant({
  'communityFocused' : IDL.Null,
  'excited' : IDL.Null,
  'trustedAdvisor' : IDL.Null,
});
export const Platform = IDL.Variant({
  'tiktok' : IDL.Null,
  'instagram' : IDL.Null,
  'facebook' : IDL.Null,
});
export const CampaignObjective = IDL.Variant({
  'leadGeneration' : IDL.Null,
  'testDrive' : IDL.Null,
  'brandAwareness' : IDL.Null,
});
export const OfferDetails = IDL.Record({
  'mileage' : IDL.Nat,
  'discount' : IDL.Nat,
  'price' : IDL.Nat,
});
export const VideoAsset = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'status' : IDL.Text,
  'duration' : IDL.Nat,
  'prompt' : IDL.Text,
  'aspectRatio' : IDL.Text,
});
export const ContentPackage = IDL.Record({
  'id' : IDL.Nat,
  'cta' : CTA,
  'model' : Model,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'createdBy' : IDL.Text,
  'tone' : Tone,
  'platform' : Platform,
  'campaignObjective' : CampaignObjective,
  'offerDetails' : OfferDetails,
  'caption' : IDL.Text,
  'videoAssets' : IDL.Vec(VideoAsset),
  'postingChecklist' : IDL.Vec(IDL.Text),
  'shotList' : IDL.Vec(IDL.Text),
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'testDriveScheduled' : IDL.Null,
  'contacted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'contactInfo' : IDL.Text,
  'consent' : IDL.Bool,
  'timeframe' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Vec(IDL.Text),
  'contentPackageId' : IDL.Nat,
  'vehicleInterest' : IDL.Text,
  'nextFollowUpDate' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHashtagsToContentPackage' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addLeadNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContentPackage' : IDL.Func([ContentPackage], [], []),
  'createExternalContentPackage' : IDL.Func([ContentPackage], [], []),
  'createLead' : IDL.Func([Lead], [], []),
  'getAllContentPackageIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getAllContentPackages' : IDL.Func([], [IDL.Vec(ContentPackage)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentPackage' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContentPackage)],
      ['query'],
    ),
  'getContentPackageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getContentPackagesByCreator' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContentPackage)],
      ['query'],
    ),
  'getExternalContentPackage' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContentPackage)],
      ['query'],
    ),
  'getExternalContentPackages' : IDL.Func(
      [],
      [IDL.Vec(ContentPackage)],
      ['query'],
    ),
  'getLeadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getNextContentPackageId' : IDL.Func([], [IDL.Nat], ['query']),
  'getNextLeadId' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeVideoAsset' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveExternalVideoAsset' : IDL.Func([IDL.Nat, VideoAsset], [], []),
  'saveVideoAsset' : IDL.Func([IDL.Nat, VideoAsset], [], []),
  'updateExternalContentPackage' : IDL.Func([IDL.Nat, ContentPackage], [], []),
  'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [], []),
  'updateVideoAssetStatus' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CTA = IDL.Variant({
    'scheduleTestDrive' : IDL.Null,
    'visitDealership' : IDL.Null,
    'getQuote' : IDL.Null,
  });
  const Model = IDL.Variant({
    'mustang' : IDL.Null,
    'f150' : IDL.Null,
    'explorer' : IDL.Null,
  });
  const Time = IDL.Int;
  const Tone = IDL.Variant({
    'communityFocused' : IDL.Null,
    'excited' : IDL.Null,
    'trustedAdvisor' : IDL.Null,
  });
  const Platform = IDL.Variant({
    'tiktok' : IDL.Null,
    'instagram' : IDL.Null,
    'facebook' : IDL.Null,
  });
  const CampaignObjective = IDL.Variant({
    'leadGeneration' : IDL.Null,
    'testDrive' : IDL.Null,
    'brandAwareness' : IDL.Null,
  });
  const OfferDetails = IDL.Record({
    'mileage' : IDL.Nat,
    'discount' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const VideoAsset = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'status' : IDL.Text,
    'duration' : IDL.Nat,
    'prompt' : IDL.Text,
    'aspectRatio' : IDL.Text,
  });
  const ContentPackage = IDL.Record({
    'id' : IDL.Nat,
    'cta' : CTA,
    'model' : Model,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'createdBy' : IDL.Text,
    'tone' : Tone,
    'platform' : Platform,
    'campaignObjective' : CampaignObjective,
    'offerDetails' : OfferDetails,
    'caption' : IDL.Text,
    'videoAssets' : IDL.Vec(VideoAsset),
    'postingChecklist' : IDL.Vec(IDL.Text),
    'shotList' : IDL.Vec(IDL.Text),
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'testDriveScheduled' : IDL.Null,
    'contacted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'contactInfo' : IDL.Text,
    'consent' : IDL.Bool,
    'timeframe' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Vec(IDL.Text),
    'contentPackageId' : IDL.Nat,
    'vehicleInterest' : IDL.Text,
    'nextFollowUpDate' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHashtagsToContentPackage' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addLeadNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContentPackage' : IDL.Func([ContentPackage], [], []),
    'createExternalContentPackage' : IDL.Func([ContentPackage], [], []),
    'createLead' : IDL.Func([Lead], [], []),
    'getAllContentPackageIds' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getAllContentPackages' : IDL.Func(
        [],
        [IDL.Vec(ContentPackage)],
        ['query'],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentPackage' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContentPackage)],
        ['query'],
      ),
    'getContentPackageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getContentPackagesByCreator' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContentPackage)],
        ['query'],
      ),
    'getExternalContentPackage' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContentPackage)],
        ['query'],
      ),
    'getExternalContentPackages' : IDL.Func(
        [],
        [IDL.Vec(ContentPackage)],
        ['query'],
      ),
    'getLeadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getNextContentPackageId' : IDL.Func([], [IDL.Nat], ['query']),
    'getNextLeadId' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeVideoAsset' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveExternalVideoAsset' : IDL.Func([IDL.Nat, VideoAsset], [], []),
    'saveVideoAsset' : IDL.Func([IDL.Nat, VideoAsset], [], []),
    'updateExternalContentPackage' : IDL.Func(
        [IDL.Nat, ContentPackage],
        [],
        [],
      ),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [], []),
    'updateVideoAssetStatus' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };