/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CTA = { 'scheduleTestDrive' : null } |
  { 'visitDealership' : null } |
  { 'getQuote' : null };
export type CampaignObjective = { 'leadGeneration' : null } |
  { 'testDrive' : null } |
  { 'brandAwareness' : null };
export interface ContentPackage {
  'id' : bigint,
  'cta' : CTA,
  'model' : Model,
  'hashtags' : Array<string>,
  'createdAt' : Time,
  'createdBy' : string,
  'tone' : Tone,
  'platform' : Platform,
  'campaignObjective' : CampaignObjective,
  'offerDetails' : OfferDetails,
  'caption' : string,
  'videoAssets' : Array<VideoAsset>,
  'postingChecklist' : Array<string>,
  'shotList' : Array<string>,
}
export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'contactInfo' : string,
  'consent' : boolean,
  'timeframe' : string,
  'name' : string,
  'notes' : Array<string>,
  'contentPackageId' : bigint,
  'vehicleInterest' : string,
  'nextFollowUpDate' : Time,
}
export type LeadStatus = { 'new' : null } |
  { 'won' : null } |
  { 'lost' : null } |
  { 'testDriveScheduled' : null } |
  { 'contacted' : null } |
  { 'qualified' : null };
export type Model = { 'mustang' : null } |
  { 'f150' : null } |
  { 'explorer' : null };
export interface OfferDetails {
  'mileage' : bigint,
  'discount' : bigint,
  'price' : bigint,
}
export type Platform = { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'facebook' : null };
export type Time = bigint;
export type Tone = { 'communityFocused' : null } |
  { 'excited' : null } |
  { 'trustedAdvisor' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoAsset {
  'id' : bigint,
  'url' : string,
  'status' : string,
  'duration' : bigint,
  'prompt' : string,
  'aspectRatio' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHashtagsToContentPackage' : ActorMethod<
    [bigint, Array<string>],
    undefined
  >,
  'addLeadNote' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContentPackage' : ActorMethod<[ContentPackage], undefined>,
  'createExternalContentPackage' : ActorMethod<[ContentPackage], undefined>,
  'createLead' : ActorMethod<[Lead], undefined>,
  'getAllContentPackageIds' : ActorMethod<[], Array<bigint>>,
  'getAllContentPackages' : ActorMethod<[], Array<ContentPackage>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentPackage' : ActorMethod<[bigint], [] | [ContentPackage]>,
  'getContentPackageCount' : ActorMethod<[], bigint>,
  'getContentPackagesByCreator' : ActorMethod<[string], Array<ContentPackage>>,
  'getExternalContentPackage' : ActorMethod<[bigint], [] | [ContentPackage]>,
  'getExternalContentPackages' : ActorMethod<[], Array<ContentPackage>>,
  'getLeadCount' : ActorMethod<[], bigint>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getNextContentPackageId' : ActorMethod<[], bigint>,
  'getNextLeadId' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeVideoAsset' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveExternalVideoAsset' : ActorMethod<[bigint, VideoAsset], undefined>,
  'saveVideoAsset' : ActorMethod<[bigint, VideoAsset], undefined>,
  'updateExternalContentPackage' : ActorMethod<
    [bigint, ContentPackage],
    undefined
  >,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], undefined>,
  'updateVideoAssetStatus' : ActorMethod<[bigint, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];