/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface OfferDetails {
    mileage: bigint;
    discount: bigint;
    price: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface VideoAsset {
    id: bigint;
    url: string;
    status: string;
    duration: bigint;
    prompt: string;
    aspectRatio: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lead {
    id: bigint;
    status: LeadStatus;
    contactInfo: string;
    consent: boolean;
    timeframe: string;
    name: string;
    notes: Array<string>;
    contentPackageId: bigint;
    vehicleInterest: string;
    nextFollowUpDate: Time;
}
export interface ContentPackage {
    id: bigint;
    cta: CTA;
    model: Model;
    hashtags: Array<string>;
    createdAt: Time;
    createdBy: string;
    tone: Tone;
    platform: Platform;
    campaignObjective: CampaignObjective;
    offerDetails: OfferDetails;
    caption: string;
    videoAssets: Array<VideoAsset>;
    postingChecklist: Array<string>;
    shotList: Array<string>;
}
export interface UserProfile {
    name: string;
}
export enum CTA {
    scheduleTestDrive = "scheduleTestDrive",
    visitDealership = "visitDealership",
    getQuote = "getQuote"
}
export enum CampaignObjective {
    leadGeneration = "leadGeneration",
    testDrive = "testDrive",
    brandAwareness = "brandAwareness"
}
export enum LeadStatus {
    new_ = "new",
    won = "won",
    lost = "lost",
    testDriveScheduled = "testDriveScheduled",
    contacted = "contacted",
    qualified = "qualified"
}
export enum Model {
    mustang = "mustang",
    f150 = "f150",
    explorer = "explorer"
}
export enum Platform {
    tiktok = "tiktok",
    instagram = "instagram",
    facebook = "facebook"
}
export enum Tone {
    communityFocused = "communityFocused",
    excited = "excited",
    trustedAdvisor = "trustedAdvisor"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addHashtagsToContentPackage(id: bigint, hashtags: Array<string>): Promise<void>;
    addLeadNote(id: bigint, note: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createContentPackage(contentPackage: ContentPackage): Promise<void>;
    createExternalContentPackage(contentPackage: ContentPackage): Promise<void>;
    createLead(lead: Lead): Promise<void>;
    getAllContentPackageIds(): Promise<Array<bigint>>;
    getAllContentPackages(): Promise<Array<ContentPackage>>;
    getAllLeads(): Promise<Array<Lead>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContentPackage(id: bigint): Promise<ContentPackage | null>;
    getContentPackageCount(): Promise<bigint>;
    getContentPackagesByCreator(_creator: string): Promise<Array<ContentPackage>>;
    getExternalContentPackage(id: bigint): Promise<ContentPackage | null>;
    getExternalContentPackages(): Promise<Array<ContentPackage>>;
    getLeadCount(): Promise<bigint>;
    getLeads(): Promise<Array<Lead>>;
    getNextContentPackageId(): Promise<bigint>;
    getNextLeadId(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeVideoAsset(contentPackageId: bigint, videoId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveExternalVideoAsset(id: bigint, video: VideoAsset): Promise<void>;
    saveVideoAsset(id: bigint, video: VideoAsset): Promise<void>;
    updateExternalContentPackage(_id: bigint, contentPackage: ContentPackage): Promise<void>;
    updateLeadStatus(id: bigint, status: LeadStatus): Promise<void>;
    updateVideoAssetStatus(contentPackageId: bigint, videoId: bigint, newStatus: string): Promise<void>;
}
import type { CTA as _CTA, CampaignObjective as _CampaignObjective, ContentPackage as _ContentPackage, Lead as _Lead, LeadStatus as _LeadStatus, Model as _Model, OfferDetails as _OfferDetails, Platform as _Platform, Time as _Time, Tone as _Tone, UserProfile as _UserProfile, UserRole as _UserRole, VideoAsset as _VideoAsset, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addHashtagsToContentPackage(arg0: bigint, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHashtagsToContentPackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHashtagsToContentPackage(arg0, arg1);
            return result;
        }
    }
    async addLeadNote(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadNote(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createContentPackage(arg0: ContentPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createContentPackage(to_candid_ContentPackage_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContentPackage(to_candid_ContentPackage_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createExternalContentPackage(arg0: ContentPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createExternalContentPackage(to_candid_ContentPackage_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExternalContentPackage(to_candid_ContentPackage_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createLead(arg0: Lead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_Lead_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_Lead_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllContentPackageIds(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentPackageIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentPackageIds();
            return result;
        }
    }
    async getAllContentPackages(): Promise<Array<ContentPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContentPackages();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContentPackages();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentPackage(arg0: bigint): Promise<ContentPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentPackage(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentPackage(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentPackageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentPackageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentPackageCount();
            return result;
        }
    }
    async getContentPackagesByCreator(arg0: string): Promise<Array<ContentPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentPackagesByCreator(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentPackagesByCreator(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExternalContentPackage(arg0: bigint): Promise<ContentPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExternalContentPackage(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExternalContentPackage(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExternalContentPackages(): Promise<Array<ContentPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExternalContentPackages();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExternalContentPackages();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadCount();
            return result;
        }
    }
    async getLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextContentPackageId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextContentPackageId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextContentPackageId();
            return result;
        }
    }
    async getNextLeadId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextLeadId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextLeadId();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeVideoAsset(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVideoAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVideoAsset(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveExternalVideoAsset(arg0: bigint, arg1: VideoAsset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveExternalVideoAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveExternalVideoAsset(arg0, arg1);
            return result;
        }
    }
    async saveVideoAsset(arg0: bigint, arg1: VideoAsset): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVideoAsset(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVideoAsset(arg0, arg1);
            return result;
        }
    }
    async updateExternalContentPackage(arg0: bigint, arg1: ContentPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExternalContentPackage(arg0, to_candid_ContentPackage_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExternalContentPackage(arg0, to_candid_ContentPackage_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeadStatus(arg0: bigint, arg1: LeadStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateVideoAssetStatus(arg0: bigint, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVideoAssetStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVideoAssetStatus(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_CTA_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CTA): CTA {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_CampaignObjective_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CampaignObjective): CampaignObjective {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ContentPackage_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentPackage): ContentPackage {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Model_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Model): Model {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Tone_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tone): Tone {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentPackage]): ContentPackage | null {
    return value.length === 0 ? null : from_candid_ContentPackage_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cta: _CTA;
    model: _Model;
    hashtags: Array<string>;
    createdAt: _Time;
    createdBy: string;
    tone: _Tone;
    platform: _Platform;
    campaignObjective: _CampaignObjective;
    offerDetails: _OfferDetails;
    caption: string;
    videoAssets: Array<_VideoAsset>;
    postingChecklist: Array<string>;
    shotList: Array<string>;
}): {
    id: bigint;
    cta: CTA;
    model: Model;
    hashtags: Array<string>;
    createdAt: Time;
    createdBy: string;
    tone: Tone;
    platform: Platform;
    campaignObjective: CampaignObjective;
    offerDetails: OfferDetails;
    caption: string;
    videoAssets: Array<VideoAsset>;
    postingChecklist: Array<string>;
    shotList: Array<string>;
} {
    return {
        id: value.id,
        cta: from_candid_CTA_n29(_uploadFile, _downloadFile, value.cta),
        model: from_candid_Model_n31(_uploadFile, _downloadFile, value.model),
        hashtags: value.hashtags,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tone: from_candid_Tone_n33(_uploadFile, _downloadFile, value.tone),
        platform: from_candid_Platform_n35(_uploadFile, _downloadFile, value.platform),
        campaignObjective: from_candid_CampaignObjective_n37(_uploadFile, _downloadFile, value.campaignObjective),
        offerDetails: value.offerDetails,
        caption: value.caption,
        videoAssets: value.videoAssets,
        postingChecklist: value.postingChecklist,
        shotList: value.shotList
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    contactInfo: string;
    consent: boolean;
    timeframe: string;
    name: string;
    notes: Array<string>;
    contentPackageId: bigint;
    vehicleInterest: string;
    nextFollowUpDate: _Time;
}): {
    id: bigint;
    status: LeadStatus;
    contactInfo: string;
    consent: boolean;
    timeframe: string;
    name: string;
    notes: Array<string>;
    contentPackageId: bigint;
    vehicleInterest: string;
    nextFollowUpDate: Time;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n42(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        consent: value.consent,
        timeframe: value.timeframe,
        name: value.name,
        notes: value.notes,
        contentPackageId: value.contentPackageId,
        vehicleInterest: value.vehicleInterest,
        nextFollowUpDate: value.nextFollowUpDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduleTestDrive: null;
} | {
    visitDealership: null;
} | {
    getQuote: null;
}): CTA {
    return "scheduleTestDrive" in value ? CTA.scheduleTestDrive : "visitDealership" in value ? CTA.visitDealership : "getQuote" in value ? CTA.getQuote : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mustang: null;
} | {
    f150: null;
} | {
    explorer: null;
}): Model {
    return "mustang" in value ? Model.mustang : "f150" in value ? Model.f150 : "explorer" in value ? Model.explorer : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    communityFocused: null;
} | {
    excited: null;
} | {
    trustedAdvisor: null;
}): Tone {
    return "communityFocused" in value ? Tone.communityFocused : "excited" in value ? Tone.excited : "trustedAdvisor" in value ? Tone.trustedAdvisor : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiktok: null;
} | {
    instagram: null;
} | {
    facebook: null;
}): Platform {
    return "tiktok" in value ? Platform.tiktok : "instagram" in value ? Platform.instagram : "facebook" in value ? Platform.facebook : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadGeneration: null;
} | {
    testDrive: null;
} | {
    brandAwareness: null;
}): CampaignObjective {
    return "leadGeneration" in value ? CampaignObjective.leadGeneration : "testDrive" in value ? CampaignObjective.testDrive : "brandAwareness" in value ? CampaignObjective.brandAwareness : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    won: null;
} | {
    lost: null;
} | {
    testDriveScheduled: null;
} | {
    contacted: null;
} | {
    qualified: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "won" in value ? LeadStatus.won : "lost" in value ? LeadStatus.lost : "testDriveScheduled" in value ? LeadStatus.testDriveScheduled : "contacted" in value ? LeadStatus.contacted : "qualified" in value ? LeadStatus.qualified : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentPackage>): Array<ContentPackage> {
    return value.map((x)=>from_candid_ContentPackage_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n40(_uploadFile, _downloadFile, x));
}
function to_candid_CTA_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CTA): _CTA {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CampaignObjective_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignObjective): _CampaignObjective {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ContentPackage_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentPackage): _ContentPackage {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Lead_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lead): _Lead {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Model_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): _Model {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Tone_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tone): _Tone {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cta: CTA;
    model: Model;
    hashtags: Array<string>;
    createdAt: Time;
    createdBy: string;
    tone: Tone;
    platform: Platform;
    campaignObjective: CampaignObjective;
    offerDetails: OfferDetails;
    caption: string;
    videoAssets: Array<VideoAsset>;
    postingChecklist: Array<string>;
    shotList: Array<string>;
}): {
    id: bigint;
    cta: _CTA;
    model: _Model;
    hashtags: Array<string>;
    createdAt: _Time;
    createdBy: string;
    tone: _Tone;
    platform: _Platform;
    campaignObjective: _CampaignObjective;
    offerDetails: _OfferDetails;
    caption: string;
    videoAssets: Array<_VideoAsset>;
    postingChecklist: Array<string>;
    shotList: Array<string>;
} {
    return {
        id: value.id,
        cta: to_candid_CTA_n12(_uploadFile, _downloadFile, value.cta),
        model: to_candid_Model_n14(_uploadFile, _downloadFile, value.model),
        hashtags: value.hashtags,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        tone: to_candid_Tone_n16(_uploadFile, _downloadFile, value.tone),
        platform: to_candid_Platform_n18(_uploadFile, _downloadFile, value.platform),
        campaignObjective: to_candid_CampaignObjective_n20(_uploadFile, _downloadFile, value.campaignObjective),
        offerDetails: value.offerDetails,
        caption: value.caption,
        videoAssets: value.videoAssets,
        postingChecklist: value.postingChecklist,
        shotList: value.shotList
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: LeadStatus;
    contactInfo: string;
    consent: boolean;
    timeframe: string;
    name: string;
    notes: Array<string>;
    contentPackageId: bigint;
    vehicleInterest: string;
    nextFollowUpDate: Time;
}): {
    id: bigint;
    status: _LeadStatus;
    contactInfo: string;
    consent: boolean;
    timeframe: string;
    name: string;
    notes: Array<string>;
    contentPackageId: bigint;
    vehicleInterest: string;
    nextFollowUpDate: _Time;
} {
    return {
        id: value.id,
        status: to_candid_LeadStatus_n24(_uploadFile, _downloadFile, value.status),
        contactInfo: value.contactInfo,
        consent: value.consent,
        timeframe: value.timeframe,
        name: value.name,
        notes: value.notes,
        contentPackageId: value.contentPackageId,
        vehicleInterest: value.vehicleInterest,
        nextFollowUpDate: value.nextFollowUpDate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CTA): {
    scheduleTestDrive: null;
} | {
    visitDealership: null;
} | {
    getQuote: null;
} {
    return value == CTA.scheduleTestDrive ? {
        scheduleTestDrive: null
    } : value == CTA.visitDealership ? {
        visitDealership: null
    } : value == CTA.getQuote ? {
        getQuote: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): {
    mustang: null;
} | {
    f150: null;
} | {
    explorer: null;
} {
    return value == Model.mustang ? {
        mustang: null
    } : value == Model.f150 ? {
        f150: null
    } : value == Model.explorer ? {
        explorer: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tone): {
    communityFocused: null;
} | {
    excited: null;
} | {
    trustedAdvisor: null;
} {
    return value == Tone.communityFocused ? {
        communityFocused: null
    } : value == Tone.excited ? {
        excited: null
    } : value == Tone.trustedAdvisor ? {
        trustedAdvisor: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    tiktok: null;
} | {
    instagram: null;
} | {
    facebook: null;
} {
    return value == Platform.tiktok ? {
        tiktok: null
    } : value == Platform.instagram ? {
        instagram: null
    } : value == Platform.facebook ? {
        facebook: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CampaignObjective): {
    leadGeneration: null;
} | {
    testDrive: null;
} | {
    brandAwareness: null;
} {
    return value == CampaignObjective.leadGeneration ? {
        leadGeneration: null
    } : value == CampaignObjective.testDrive ? {
        testDrive: null
    } : value == CampaignObjective.brandAwareness ? {
        brandAwareness: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    won: null;
} | {
    lost: null;
} | {
    testDriveScheduled: null;
} | {
    contacted: null;
} | {
    qualified: null;
} {
    return value == LeadStatus.new ? {
        new_: null
    } : value == LeadStatus.won ? {
        won: null
    } : value == LeadStatus.lost ? {
        lost: null
    } : value == LeadStatus.testDriveScheduled ? {
        testDriveScheduled: null
    } : value == LeadStatus.contacted ? {
        contacted: null
    } : value == LeadStatus.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
